-- 코드를 입력하세요
SELECT
    P.PRODUCT_ID
    ,P.PRODUCT_NAME
    ,SUM(P.PRICE * O.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT P LEFT JOIN FOOD_ORDER O ON P.PRODUCT_ID = O.PRODUCT_ID
WHERE O.PRODUCE_DATE LIKE '2022-05%'
GROUP BY 1,2
ORDER BY TOTAL_SALES DESC, P.PRODUCT_ID ASC

# select
# *
# from
# FOOD_PRODUCT P inner JOIN FOOD_ORDER O ON P.PRODUCT_ID = O.PRODUCT_ID
# WHERE O.PRODUCE_DATE LIKE '2022-05%'